<?php

return [
    [
        'product' => 'Coconut Water (85%, 100%, with flavors)',
        'pet' => '250ml, 280ml, 350ml, 500ml',
        'tetra_pak' => '1L',
        'sleek_can' => '310ml',
        'aluminum_can' => '310ml, 500ml',
        'tin_can' => '330ml, 520ml',
        'carnation_can' => '-',
        'bulk' => '5L, 10L, 20L, 200L',
    ],
    [
        'product' => 'Coconut Milk Drink in different flavors (for drinking)',
        'pet' => '250ml, 280ml, 350ml, 500ml',
        'tetra_pak' => '1L',
        'sleek_can' => '310ml',
        'aluminum_can' => '310ml, 500ml',
        'tin_can' => '-',
        'carnation_can' => '-',
        'bulk' => '-',
    ],
    [
        'product' => 'Coconut Milk in different fat contents (for cooking)',
        'pet' => '200ml',
        'tetra_pak' => '1L',
        'sleek_can' => '-',
        'aluminum_can' => '-',
        'tin_can' => '165ml, 400ml, 2900ml',
        'carnation_can' => '-',
        'bulk' => '5L, 10L, 20L, 200L',
    ],
    [
        'product' => 'Roasted Coconut Water',
        'pet' => '250ml, 280ml, 350ml, 500ml',
        'tetra_pak' => '1L',
        'sleek_can' => '310ml',
        'aluminum_can' => '310ml, 500ml',
        'tin_can' => '330ml, 520ml',
        'carnation_can' => '-',
        'bulk' => '-',
    ],
    [
        'product' => 'Organic Coconut Water / Coconut Milk',
        'pet' => '250 ml, 280 ml, 350 ml, 500 ml',
        'tetra_pak' => '1L',
        'sleek_can' => '310 ml',
        'aluminum_can' => '310 ml, 500 ml',
        'tin_can' => '330 ml, 520 ml, 400 ml',
        'carnation_can' => '-',
        'bulk' => '5L, 10L, 20L, 200L',
    ],
    [
        'product' => 'Sweetened Condensed Coconut Milk',
        'pet' => '-',
        'tetra_pak' => '-',
        'sleek_can' => '-',
        'aluminum_can' => '-',
        'tin_can' => '330 g',
        'carnation_can' => '-',
        'bulk' => '-',
    ],
    [
        'product' => 'Coconut Whipping Cream (with / without sugar)',
        'pet' => '-',
        'tetra_pak' => '1L',
        'sleek_can' => '-',
        'aluminum_can' => '-',
        'tin_can' => '400ml',
        'carnation_can' => '-',
        'bulk' => '-',
    ],
    [
        'product' => 'Evaporated Coconut Milk (with / without sugar)',
        'pet' => '-',
        'tetra_pak' => '1L',
        'sleek_can' => '-',
        'aluminum_can' => '-',
        'tin_can' => '400ml',
        'carnation_can' => '354 g',
        'bulk' => '-',
    ],
    [
        'product' => 'Coconut Soup',
        'pet' => '250 ml, 280 ml, 350 ml, 500 ml.',
        'tetra_pak' => '1L',
        'sleek_can' => '-',
        'aluminum_can' => '-',
        'tin_can' => '-',
        'carnation_can' => '-',
        'bulk' => '5L, 10L, 20L, 200L',
    ],
];
